


export enum Nodes {
  RETRIEVE_KNOWLEDGE = 'RETRIEVE_KNOWLEDGE',
  FILTER_RELEVEANT = 'FILTER_RELEVEANT',
  RESPONSE_INSUFFICIENT = 'RESPONSE_INSUFFICIENT',
  ANSWER = 'ANSWER'
}


export enum InferenceResponseType {
  ANSWER = "ANSWER",
  INSUFFICIENT = "INSUFFICIENT",
} 